### ISSUE TITLE
Guys I need some help!

### ISSUE THREAD

**Issue by CrazyNicolas** [PacktPublishing/PyTorch-1.x-Reinforcement-Learning-Cookbook#2]
dqn.py in Chapter 7 is not working, I copy the code and run it in my Jupyter notebook, but the total_reward still remains -200 after 800 epochs. It is quite different from what the book said! So I wonder if the code is right? I will try by myself and if I figure it out I will give you a request pull but better it is solved by you. Thanks!

**Comment by CrazyNicolas** [comment]
I already figure out what happens here!
If you use this code to solve CartPole-V0, it is useful.
However, MountainCar is more conplex so this algorithm can't.

**Comment by haydenliu** [comment]
As mentioned in the book, MountainCar is very complicated, hence we only present a sample solution and you are encouraged to fine-tune the hyperparameters.

**Comment by CrazyNicolas** [comment]
> As mentioned in the book, MountainCar is very complicated, hence we only present a sample solution and you are encouraged to fine-tune the hyperparameters.

agree！
